In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
namus = pd.read_csv('./data/namus_clean.csv', on_bad_lines = 'warn')
namus

,Case Number,DLC,Legal Last Name,Legal Last Name CRCT,Legal First Name,Legal First Name CRCT,Missing Age,City,County,State,Biological Sex,Race / Ethnicity,Date Modified,Unnamed: 13,Race / Ethnicity 1,Race/Ethn 2,Race/Ethn 3,Race/Ethn 4,Unnamed: 18
0,MP112724,12/6/2023,Rubi Jr,Rubi Jr,Jose,Jose,16 Years,West Hartford,Hartford,CT,Male,Black / African American,12/7/2023,NaN,Black / African American,NaN,NaN,NaN,NaN
1,MP112723,12/5/2023,Fix,Fix,Malachi,Malachi,16 Years,Okmulgee,Okmulgee,OK,Male,White / Caucasian,12/7/2023,NaN,White / Caucasian,NaN,NaN,NaN,NaN
2,MP112746,12/2/2023,Erickson,Erickson,Brian,Brian,40 Years,Healy Lake,Fairbanks North Star,AK,Male,American Indian / Alaska Native,12/6/2023,NaN,American Indian / Alaska Native,NaN,NaN,NaN,NaN
3,MP112440,11/30/2023,Stites,Stites,Jeremiah,Jeremiah,15 Years,Van Buren,Crawford,AR,Male,Black / African American,12/5/2023,NaN,Black / African American,NaN,NaN,NaN,NaN
4,MP112488,11/30/2023,CONKLIN,Conklin,PEYTON,Peyton,16 Years,Goodyear,Maricopa,AZ,Female,Asian,12/4/2023,NaN,Asian,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24034,MP24452,7/1/1925,Bartlett,Bartlett,Gerald,Gerald,21 Years,Davil's Lake,Ramsey,ND,Male,White / Caucasian,7/26/2023,NaN,White / Caucasian,NaN,NaN,NaN,NaN
24035,MP25633,1/1/1920,Myers,Myers,Sigmund,Sigmund,44 Years,Portland,Multnomah,OR,Male,White / Caucasian,7/26/2023,NaN,White / Caucasian,NaN,NaN,NaN,NaN
24036,MP24464,4/23/1916,Gates,Gates,John,John,33 Years,Longmont,Boulder,CO,Male,White / Caucasian,5/26/2023,NaN,White / Caucasian,NaN,NaN,NaN,NaN
24037,MP24522,11/1/1915,Davis,Davis,Noel,Noel,16 Years,Reno,Washoe,NV,Male,White / Caucasian,10/4/2023,NaN,White / Caucasian,NaN,NaN,NaN,NaN
24038,MP9137,1/1/1902,Cravens,Cravens,Elijah,Elijah,30 - 40 Years,Okmulgee,Okmulgee,OK,Male,White / Caucasian,10/4/2023,NaN,White / Caucasian,NaN,NaN,NaN,NaN

In [3]:
namus['DLC'] = pd.to_datetime(namus['DLC'])
namus['Date Modified'] = pd.to_datetime(namus['Date Modified'])
namus

,Case Number,DLC,Legal Last Name,Legal Last Name CRCT,Legal First Name,Legal First Name CRCT,Missing Age,City,County,State,Biological Sex,Race / Ethnicity,Date Modified,Unnamed: 13,Race / Ethnicity 1,Race/Ethn 2,Race/Ethn 3,Race/Ethn 4,Unnamed: 18
0,MP112724,2023-12-06,Rubi Jr,Rubi Jr,Jose,Jose,16 Years,West Hartford,Hartford,CT,Male,Black / African American,2023-12-07,NaN,Black / African American,NaN,NaN,NaN,NaN
1,MP112723,2023-12-05,Fix,Fix,Malachi,Malachi,16 Years,Okmulgee,Okmulgee,OK,Male,White / Caucasian,2023-12-07,NaN,White / Caucasian,NaN,NaN,NaN,NaN
2,MP112746,2023-12-02,Erickson,Erickson,Brian,Brian,40 Years,Healy Lake,Fairbanks North Star,AK,Male,American Indian / Alaska Native,2023-12-06,NaN,American Indian / Alaska Native,NaN,NaN,NaN,NaN
3,MP112440,2023-11-30,Stites,Stites,Jeremiah,Jeremiah,15 Years,Van Buren,Crawford,AR,Male,Black / African American,2023-12-05,NaN,Black / African American,NaN,NaN,NaN,NaN
4,MP112488,2023-11-30,CONKLIN,Conklin,PEYTON,Peyton,16 Years,Goodyear,Maricopa,AZ,Female,Asian,2023-12-04,NaN,Asian,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24034,MP24452,1925-07-01,Bartlett,Bartlett,Gerald,Gerald,21 Years,Davil's Lake,Ramsey,ND,Male,White / Caucasian,2023-07-26,NaN,White / Caucasian,NaN,NaN,NaN,NaN
24035,MP25633,1920-01-01,Myers,Myers,Sigmund,Sigmund,44 Years,Portland,Multnomah,OR,Male,White / Caucasian,2023-07-26,NaN,White / Caucasian,NaN,NaN,NaN,NaN
24036,MP24464,1916-04-23,Gates,Gates,John,John,33 Years,Longmont,Boulder,CO,Male,White / Caucasian,2023-05-26,NaN,White / Caucasian,NaN,NaN,NaN,NaN
24037,MP24522,1915-11-01,Davis,Davis,Noel,Noel,16 Years,Reno,Washoe,NV,Male,White / Caucasian,2023-10-04,NaN,White / Caucasian,NaN,NaN,NaN,NaN
24038,MP9137,1902-01-01,Cravens,Cravens,Elijah,Elijah,30 - 40 Years,Okmulgee,Okmulgee,OK,Male,White / Caucasian,2023-10-04,NaN,White / Caucasian,NaN,NaN,NaN,NaN

In [4]:
namus['Missing Age'] = namus['Missing Age'].str.extract(r'^(\d{2})', expand = False)

In [5]:
namus['Race/Ethn 5'] = namus['Unnamed: 18']

In [6]:
namus = namus.drop(['Legal Last Name', 'Legal First Name', 'Unnamed: 13', 'Unnamed: 18'], axis=1)

In [7]:
namus

,Case Number,DLC,Legal Last Name CRCT,Legal First Name CRCT,Missing Age,City,County,State,Biological Sex,Race / Ethnicity,Date Modified,Race / Ethnicity 1,Race/Ethn 2,Race/Ethn 3,Race/Ethn 4,Race/Ethn 5
0,MP112724,2023-12-06,Rubi Jr,Jose,16,West Hartford,Hartford,CT,Male,Black / African American,2023-12-07,Black / African American,NaN,NaN,NaN,NaN
1,MP112723,2023-12-05,Fix,Malachi,16,Okmulgee,Okmulgee,OK,Male,White / Caucasian,2023-12-07,White / Caucasian,NaN,NaN,NaN,NaN
2,MP112746,2023-12-02,Erickson,Brian,40,Healy Lake,Fairbanks North Star,AK,Male,American Indian / Alaska Native,2023-12-06,American Indian / Alaska Native,NaN,NaN,NaN,NaN
3,MP112440,2023-11-30,Stites,Jeremiah,15,Van Buren,Crawford,AR,Male,Black / African American,2023-12-05,Black / African American,NaN,NaN,NaN,NaN
4,MP112488,2023-11-30,Conklin,Peyton,16,Goodyear,Maricopa,AZ,Female,Asian,2023-12-04,Asian,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24034,MP24452,1925-07-01,Bartlett,Gerald,21,Davil's Lake,Ramsey,ND,Male,White / Caucasian,2023-07-26,White / Caucasian,NaN,NaN,NaN,NaN
24035,MP25633,1920-01-01,Myers,Sigmund,44,Portland,Multnomah,OR,Male,White / Caucasian,2023-07-26,White / Caucasian,NaN,NaN,NaN,NaN
24036,MP24464,1916-04-23,Gates,John,33,Longmont,Boulder,CO,Male,White / Caucasian,2023-05-26,White / Caucasian,NaN,NaN,NaN,NaN
24037,MP24522,1915-11-01,Davis,Noel,16,Reno,Washoe,NV,Male,White / Caucasian,2023-10-04,White / Caucasian,NaN,NaN,NaN,NaN
24038,MP9137,1902-01-01,Cravens,Elijah,30,Okmulgee,Okmulgee,OK,Male,White / Caucasian,2023-10-04,White / Caucasian,NaN,NaN,NaN,NaN

In [8]:
namus = namus.rename(columns={'Legal Last Name CRCT':'Last Name', 'Legal First Name CRCT':'First Name', 'Race / Ethnicity 1':'Race/Ethn 1'})

In [9]:
namus

,Case Number,DLC,Last Name,First Name,Missing Age,City,County,State,Biological Sex,Race / Ethnicity,Date Modified,Race/Ethn 1,Race/Ethn 2,Race/Ethn 3,Race/Ethn 4,Race/Ethn 5
0,MP112724,2023-12-06,Rubi Jr,Jose,16,West Hartford,Hartford,CT,Male,Black / African American,2023-12-07,Black / African American,NaN,NaN,NaN,NaN
1,MP112723,2023-12-05,Fix,Malachi,16,Okmulgee,Okmulgee,OK,Male,White / Caucasian,2023-12-07,White / Caucasian,NaN,NaN,NaN,NaN
2,MP112746,2023-12-02,Erickson,Brian,40,Healy Lake,Fairbanks North Star,AK,Male,American Indian / Alaska Native,2023-12-06,American Indian / Alaska Native,NaN,NaN,NaN,NaN
3,MP112440,2023-11-30,Stites,Jeremiah,15,Van Buren,Crawford,AR,Male,Black / African American,2023-12-05,Black / African American,NaN,NaN,NaN,NaN
4,MP112488,2023-11-30,Conklin,Peyton,16,Goodyear,Maricopa,AZ,Female,Asian,2023-12-04,Asian,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24034,MP24452,1925-07-01,Bartlett,Gerald,21,Davil's Lake,Ramsey,ND,Male,White / Caucasian,2023-07-26,White / Caucasian,NaN,NaN,NaN,NaN
24035,MP25633,1920-01-01,Myers,Sigmund,44,Portland,Multnomah,OR,Male,White / Caucasian,2023-07-26,White / Caucasian,NaN,NaN,NaN,NaN
24036,MP24464,1916-04-23,Gates,John,33,Longmont,Boulder,CO,Male,White / Caucasian,2023-05-26,White / Caucasian,NaN,NaN,NaN,NaN
24037,MP24522,1915-11-01,Davis,Noel,16,Reno,Washoe,NV,Male,White / Caucasian,2023-10-04,White / Caucasian,NaN,NaN,NaN,NaN
24038,MP9137,1902-01-01,Cravens,Elijah,30,Okmulgee,Okmulgee,OK,Male,White / Caucasian,2023-10-04,White / Caucasian,NaN,NaN,NaN,NaN

In [10]:
namus2020 = namus.loc[namus['DLC'].dt.year == 2020]
namus2020

,Case Number,DLC,Last Name,First Name,Missing Age,City,County,State,Biological Sex,Race / Ethnicity,Date Modified,Race/Ethn 1,Race/Ethn 2,Race/Ethn 3,Race/Ethn 4,Race/Ethn 5
4121,MP77387,2020-12-31,Brown,Rupert,42,Riverton,Fremont,WY,Male,American Indian / Alaska Native,2023-04-27,American Indian / Alaska Native,NaN,NaN,NaN,NaN
4122,MP78577,2020-12-30,Fleetwood,Keyara,15,Oklahoma City,Oklahoma,OK,Female,Black / African American,2023-02-12,Black / African American,NaN,NaN,NaN,NaN
4123,MP77291,2020-12-30,Rolle,Shanyea,27,Houston,Harris,TX,Female,Black / African American,2021-03-18,Black / African American,NaN,NaN,NaN,NaN
4124,MP104066,2020-12-30,Clopton,William,33,Tupelo,Pontotoc,MS,Male,White / Caucasian,2023-06-05,White / Caucasian,NaN,NaN,NaN,NaN
4125,MP80732,2020-12-29,Ellis-Sandlin,Kayven,16,Inglis,Levy,FL,Female,White / Caucasian,2022-04-19,White / Caucasian,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5086,MP71494,2020-01-01,Jackson,Johnny,47,Long Island City,Queens,NY,Male,Black / African American,2020-08-11,Black / African American,NaN,NaN,NaN,NaN
5087,MP80267,2020-01-01,Veldhaus,Chad,48,Santa Monica,Los Angeles,CA,Male,White / Caucasian,2021-05-18,White / Caucasian,NaN,NaN,NaN,NaN
5088,MP101316,2020-01-01,Perez,Edber,30,Washington D.C.,District of Columbia,DC,Male,Hispanic / Latino,2023-03-15,Hispanic / Latino,NaN,NaN,NaN,NaN
5089,MP100111,2020-01-01,Mccallion,Leslie,67,Monterey,Monterey,CA,Male,White / Caucasian,2023-05-08,White / Caucasian,NaN,NaN,NaN,NaN
5090,MP103183,2020-01-01,Barksdale,James,39,Kansas City,Jackson,MO,Male,Black / African American,2023-07-27,Black / African American,NaN,NaN,NaN,NaN

In [11]:
namus2020.State.value_counts()

State
CA    176
TX     96
OK     77
FL     62
NY     41
TN     39
AK     34
GA     33
WA     28
LA     27
NC     25
MO     23
AR     18
NJ     18
AZ     18
MI     16
SC     16
NM     15
PA     15
MS     15
OR     15
KY     14
IL     12
CO     12
OH     12
HI     11
AL      9
MD      9
IN      9
MA      7
WI      7
ID      6
KS      6
CT      5
WV      5
NV      5
VA      5
UT      4
MT      4
MN      3
IA      3
DC      3
NE      2
DE      2
WY      2
ND      2
NH      2
PR      1
VT      1
Name: count, dtype: int64

In [12]:
pops = pd.read_csv('./data/apportionment.csv')

In [13]:
pops

,Name,Geography Type,Year,Resident Population,Percent Change in Resident Population,Resident Population Density,Resident Population Density Rank,Number of Representatives,Change in Number of Representatives,Average Apportionment Population Per Representative
0,Alabama,State,1910,"2,138,093",16.9,42.2,25.0,10.0,1.0,"213,809"
1,Alaska,State,1910,"64,356",1.2,0.1,52.0,NaN,NaN,NaN
2,Arizona,State,1910,"204,354",66.2,1.8,49.0,NaN,NaN,NaN
3,Arkansas,State,1910,"1,574,449",20.0,30.3,30.0,7.0,0.0,"224,921"
4,California,State,1910,"2,377,549",60.1,15.3,38.0,11.0,3.0,"216,051"
...,...,...,...,...,...,...,...,...,...,...
679,Midwest Region,Region,2020,"68,985,454",3.1,NaN,NaN,NaN,NaN,NaN
680,Northeast Region,Region,2020,"57,609,148",4.1,NaN,NaN,NaN,NaN,NaN
681,South Region,Region,2020,"126,266,107",10.2,NaN,NaN,NaN,NaN,NaN
682,West Region,Region,2020,"78,588,572",9.2,NaN,NaN,NaN,NaN,NaN
683,United States,Nation,2020,"331,449,281",7.4,93.8,NaN,435.0,7.0,"761,169"

In [14]:
pops20 = pops.loc[pops['Year'] == 2020]
pops20

,Name,Geography Type,Year,Resident Population,Percent Change in Resident Population,Resident Population Density,Resident Population Density Rank,Number of Representatives,Change in Number of Representatives,Average Apportionment Population Per Representative
627,Alabama,State,2020,"5,024,279",5.1,99.2,29.0,7.0,0.0,"718,579"
628,Alaska,State,2020,"733,391",3.3,1.3,52.0,1.0,0.0,"736,081"
629,Arizona,State,2020,"7,151,502",11.9,62.9,35.0,9.0,0.0,"795,436"
630,Arkansas,State,2020,"3,011,524",3.3,57.9,36.0,4.0,0.0,"753,439"
631,California,State,2020,"39,538,223",6.1,253.7,13.0,52.0,-1.0,"761,091"
632,Colorado,State,2020,"5,773,714",14.8,55.7,39.0,8.0,1.0,"722,771"
633,Connecticut,State,2020,"3,605,944",0.9,744.7,6.0,5.0,0.0,"721,660"
634,Delaware,State,2020,"989,948",10.2,508,8.0,1.0,0.0,"990,837"
635,District of Columbia,State,2020,"689,545",14.6,"11,280.00",1.0,NaN,NaN,NaN
636,Florida,State,2020,"21,538,187",14.6,401.4,10.0,28.0,1.0,"770,376"
637,Georgia,State,2020,"10,711,908",10.6,185.6,19.0,14.0,0.0,"766,091"
638,Hawaii,State,2020,"1,455,271",7.0,226.6,15.0,2.0,0.0,"730,069"
639,Idaho,State,2020,"1,839,106",17.3,22.3,46.0,2.0,0.0,"920,689"
640,Illinois,State,2020,"12,812,508",-0.1,230.8,14.0,17.0,-1.0,"754,279"
641,Indiana,State,2020,"6,785,528",4.7,189.4,18.0,9.0,0.0,"754,476"
642,Iowa,State,2020,"3,190,369",4.7,57.1,38.0,4.0,0.0,"798,102"
643,Kansas,State,2020,"2,937,880",3.0,35.9,43.0,4.0,0.0,"735,216"
644,Kentucky,State,2020,"4,505,836",3.8,114.1,25.0,6.0,0.0,"751,557"
645,Louisiana,State,2020,"4,657,757",2.7,107.8,28.0,6.0,0.0,"776,911"
646,Maine,State,2020,"1,362,359",2.6,44.2,40.0,2.0,0.0,"681,791"
647,Maryland,State,2020,"6,177,224",7.0,636.1,7.0,8.0,0.0,"773,160"
648,Massachusetts,State,2020,"7,029,917",7.4,901.2,5.0,9.0,0.0,"781,497"
649,Michigan,State,2020,"10,077,331",2.0,178,20.0,13.0,-1.0,"775,726"
650,Minnesota,State,2020,"5,706,494",7.6,71.7,32.0,8.0,0.0,"713,719"
651,Mississippi,State,2020,"2,961,279",-0.2,63.1,34.0,4.0,0.0,"740,979"
652,Missouri,State,2020,"6,154,913",2.8,89.5,30.0,8.0,0.0,"770,035"
653,Montana,State,2020,"1,084,225",9.6,7.4,50.0,2.0,1.0,"542,704"
654,Nebraska,State,2020,"1,961,504",7.4,25.5,45.0,3.0,0.0,"654,444"
655,Nevada,State,2020,"3,104,614",15.0,28.3,44.0,4.0,0.0,"777,116"
656,New Hampshire,State,2020,"1,377,529",4.6,153.8,23.0,2.0,0.0,"689,545"
657,New Jersey,State,2020,"9,288,994",5.7,"1,263.00",2.0,12.0,0.0,"774,541"
658,New Mexico,State,2020,"2,117,522",2.8,17.5,47.0,3.0,0.0,"706,740"
659,New York,State,2020,"20,201,249",4.2,428.7,9.0,26.0,-1.0,"777,529"
660,North Carolina,State,2020,"10,439,388",9.5,214.7,17.0,14.0,1.0,"746,711"
661,North Dakota,State,2020,"779,094",15.8,11.3,49.0,1.0,0.0,"779,702"
662,Ohio,State,2020,"11,799,448",2.3,288.8,12.0,15.0,-1.0,"787,257"
663,Oklahoma,State,2020,"3,959,353",5.5,57.7,37.0,5.0,0.0,"792,703"
664,Oregon,State,2020,"4,237,256",10.6,44.1,41.0,6.0,1.0,"706,917"
665,Pennsylvania,State,2020,"13,002,700",2.4,290.6,11.0,17.0,-1.0,"765,403"
666,Puerto Rico,State,2020,"3,285,874",-11.8,959.6,4.0,NaN,NaN,NaN
667,Rhode Island,State,2020,"1,097,379",4.3,"1,061.40",3.0,2.0,0.0,"549,082"
668,South Carolina,State,2020,"5,118,425",10.7,170.2,21.0,7.0,0.0,"732,102"
669,South Dakota,State,2020,"886,667",8.9,11.7,48.0,1.0,0.0,"887,770"
670,Tennessee,State,2020,"6,910,840",8.9,167.6,22.0,9.0,0.0,"768,544"
671,Texas,State,2020,"29,145,505",15.9,111.6,26.0,38.0,2.0,"767,981"
672,Utah,State,2020,"3,271,616",18.4,39.7,42.0,4.0,0.0,"818,813"
673,Vermont,State,2020,"643,077",2.8,69.8,33.0,1.0,0.0,"643,503"
674,Virginia,State,2020,"8,631,393",7.9,218.6,16.0,11.0,0.0,"786,777"
675,Washington,State,2020,"7,705,281",14.6,115.9,24.0,10.0,0.0,"771,595"
676,West Virginia,State,2020,"1,793,716",-3.2,74.6,31.0,2.0,-1.0,"897,523"
677,Wisconsin,State,2020,"5,893,718",3.6,108.8,27.0,8.0,0.0,"737,184"
678,Wyoming,State,2020,"576,851",2.3,5.9,51.0,1.0,0.0,"577,719"
679,Midwest Region,Region,2020,"68,985,454",3.1,NaN,NaN,NaN,NaN,NaN
680,Northeast Region,Region,2020,"57,609,148",4.1,NaN,NaN,NaN,NaN,NaN
681,South Region,Region,2020,"126,266,107",10.2,NaN,NaN,NaN,NaN,NaN
682,West Region,Region,2020,"78,588,572",9.2,NaN,NaN,NaN,NaN,NaN
683,United States,Nation,2020,"331,449,281",7.4,93.8,NaN,435.0,7.0,"761,169"

In [15]:
pops20state = pops20[pops20['Geography Type'] == 'State']
pops20state

,Name,Geography Type,Year,Resident Population,Percent Change in Resident Population,Resident Population Density,Resident Population Density Rank,Number of Representatives,Change in Number of Representatives,Average Apportionment Population Per Representative
627,Alabama,State,2020,"5,024,279",5.1,99.2,29.0,7.0,0.0,"718,579"
628,Alaska,State,2020,"733,391",3.3,1.3,52.0,1.0,0.0,"736,081"
629,Arizona,State,2020,"7,151,502",11.9,62.9,35.0,9.0,0.0,"795,436"
630,Arkansas,State,2020,"3,011,524",3.3,57.9,36.0,4.0,0.0,"753,439"
631,California,State,2020,"39,538,223",6.1,253.7,13.0,52.0,-1.0,"761,091"
632,Colorado,State,2020,"5,773,714",14.8,55.7,39.0,8.0,1.0,"722,771"
633,Connecticut,State,2020,"3,605,944",0.9,744.7,6.0,5.0,0.0,"721,660"
634,Delaware,State,2020,"989,948",10.2,508,8.0,1.0,0.0,"990,837"
635,District of Columbia,State,2020,"689,545",14.6,"11,280.00",1.0,NaN,NaN,NaN
636,Florida,State,2020,"21,538,187",14.6,401.4,10.0,28.0,1.0,"770,376"
637,Georgia,State,2020,"10,711,908",10.6,185.6,19.0,14.0,0.0,"766,091"
638,Hawaii,State,2020,"1,455,271",7.0,226.6,15.0,2.0,0.0,"730,069"
639,Idaho,State,2020,"1,839,106",17.3,22.3,46.0,2.0,0.0,"920,689"
640,Illinois,State,2020,"12,812,508",-0.1,230.8,14.0,17.0,-1.0,"754,279"
641,Indiana,State,2020,"6,785,528",4.7,189.4,18.0,9.0,0.0,"754,476"
642,Iowa,State,2020,"3,190,369",4.7,57.1,38.0,4.0,0.0,"798,102"
643,Kansas,State,2020,"2,937,880",3.0,35.9,43.0,4.0,0.0,"735,216"
644,Kentucky,State,2020,"4,505,836",3.8,114.1,25.0,6.0,0.0,"751,557"
645,Louisiana,State,2020,"4,657,757",2.7,107.8,28.0,6.0,0.0,"776,911"
646,Maine,State,2020,"1,362,359",2.6,44.2,40.0,2.0,0.0,"681,791"
647,Maryland,State,2020,"6,177,224",7.0,636.1,7.0,8.0,0.0,"773,160"
648,Massachusetts,State,2020,"7,029,917",7.4,901.2,5.0,9.0,0.0,"781,497"
649,Michigan,State,2020,"10,077,331",2.0,178,20.0,13.0,-1.0,"775,726"
650,Minnesota,State,2020,"5,706,494",7.6,71.7,32.0,8.0,0.0,"713,719"
651,Mississippi,State,2020,"2,961,279",-0.2,63.1,34.0,4.0,0.0,"740,979"
652,Missouri,State,2020,"6,154,913",2.8,89.5,30.0,8.0,0.0,"770,035"
653,Montana,State,2020,"1,084,225",9.6,7.4,50.0,2.0,1.0,"542,704"
654,Nebraska,State,2020,"1,961,504",7.4,25.5,45.0,3.0,0.0,"654,444"
655,Nevada,State,2020,"3,104,614",15.0,28.3,44.0,4.0,0.0,"777,116"
656,New Hampshire,State,2020,"1,377,529",4.6,153.8,23.0,2.0,0.0,"689,545"
657,New Jersey,State,2020,"9,288,994",5.7,"1,263.00",2.0,12.0,0.0,"774,541"
658,New Mexico,State,2020,"2,117,522",2.8,17.5,47.0,3.0,0.0,"706,740"
659,New York,State,2020,"20,201,249",4.2,428.7,9.0,26.0,-1.0,"777,529"
660,North Carolina,State,2020,"10,439,388",9.5,214.7,17.0,14.0,1.0,"746,711"
661,North Dakota,State,2020,"779,094",15.8,11.3,49.0,1.0,0.0,"779,702"
662,Ohio,State,2020,"11,799,448",2.3,288.8,12.0,15.0,-1.0,"787,257"
663,Oklahoma,State,2020,"3,959,353",5.5,57.7,37.0,5.0,0.0,"792,703"
664,Oregon,State,2020,"4,237,256",10.6,44.1,41.0,6.0,1.0,"706,917"
665,Pennsylvania,State,2020,"13,002,700",2.4,290.6,11.0,17.0,-1.0,"765,403"
666,Puerto Rico,State,2020,"3,285,874",-11.8,959.6,4.0,NaN,NaN,NaN
667,Rhode Island,State,2020,"1,097,379",4.3,"1,061.40",3.0,2.0,0.0,"549,082"
668,South Carolina,State,2020,"5,118,425",10.7,170.2,21.0,7.0,0.0,"732,102"
669,South Dakota,State,2020,"886,667",8.9,11.7,48.0,1.0,0.0,"887,770"
670,Tennessee,State,2020,"6,910,840",8.9,167.6,22.0,9.0,0.0,"768,544"
671,Texas,State,2020,"29,145,505",15.9,111.6,26.0,38.0,2.0,"767,981"
672,Utah,State,2020,"3,271,616",18.4,39.7,42.0,4.0,0.0,"818,813"
673,Vermont,State,2020,"643,077",2.8,69.8,33.0,1.0,0.0,"643,503"
674,Virginia,State,2020,"8,631,393",7.9,218.6,16.0,11.0,0.0,"786,777"
675,Washington,State,2020,"7,705,281",14.6,115.9,24.0,10.0,0.0,"771,595"
676,West Virginia,State,2020,"1,793,716",-3.2,74.6,31.0,2.0,-1.0,"897,523"
677,Wisconsin,State,2020,"5,893,718",3.6,108.8,27.0,8.0,0.0,"737,184"
678,Wyoming,State,2020,"576,851",2.3,5.9,51.0,1.0,0.0,"577,719"

In [16]:
pops20state = pops20state.drop(columns = ['Average Apportionment Population Per Representative', 'Change in Number of Representatives', 'Number of Representatives', 'Geography Type'])

In [17]:
pops20state

,Name,Year,Resident Population,Percent Change in Resident Population,Resident Population Density,Resident Population Density Rank
627,Alabama,2020,"5,024,279",5.1,99.2,29.0
628,Alaska,2020,"733,391",3.3,1.3,52.0
629,Arizona,2020,"7,151,502",11.9,62.9,35.0
630,Arkansas,2020,"3,011,524",3.3,57.9,36.0
631,California,2020,"39,538,223",6.1,253.7,13.0
632,Colorado,2020,"5,773,714",14.8,55.7,39.0
633,Connecticut,2020,"3,605,944",0.9,744.7,6.0
634,Delaware,2020,"989,948",10.2,508,8.0
635,District of Columbia,2020,"689,545",14.6,"11,280.00",1.0
636,Florida,2020,"21,538,187",14.6,401.4,10.0
637,Georgia,2020,"10,711,908",10.6,185.6,19.0
638,Hawaii,2020,"1,455,271",7.0,226.6,15.0
639,Idaho,2020,"1,839,106",17.3,22.3,46.0
640,Illinois,2020,"12,812,508",-0.1,230.8,14.0
641,Indiana,2020,"6,785,528",4.7,189.4,18.0
642,Iowa,2020,"3,190,369",4.7,57.1,38.0
643,Kansas,2020,"2,937,880",3.0,35.9,43.0
644,Kentucky,2020,"4,505,836",3.8,114.1,25.0
645,Louisiana,2020,"4,657,757",2.7,107.8,28.0
646,Maine,2020,"1,362,359",2.6,44.2,40.0
647,Maryland,2020,"6,177,224",7.0,636.1,7.0
648,Massachusetts,2020,"7,029,917",7.4,901.2,5.0
649,Michigan,2020,"10,077,331",2.0,178,20.0
650,Minnesota,2020,"5,706,494",7.6,71.7,32.0
651,Mississippi,2020,"2,961,279",-0.2,63.1,34.0
652,Missouri,2020,"6,154,913",2.8,89.5,30.0
653,Montana,2020,"1,084,225",9.6,7.4,50.0
654,Nebraska,2020,"1,961,504",7.4,25.5,45.0
655,Nevada,2020,"3,104,614",15.0,28.3,44.0
656,New Hampshire,2020,"1,377,529",4.6,153.8,23.0
657,New Jersey,2020,"9,288,994",5.7,"1,263.00",2.0
658,New Mexico,2020,"2,117,522",2.8,17.5,47.0
659,New York,2020,"20,201,249",4.2,428.7,9.0
660,North Carolina,2020,"10,439,388",9.5,214.7,17.0
661,North Dakota,2020,"779,094",15.8,11.3,49.0
662,Ohio,2020,"11,799,448",2.3,288.8,12.0
663,Oklahoma,2020,"3,959,353",5.5,57.7,37.0
664,Oregon,2020,"4,237,256",10.6,44.1,41.0
665,Pennsylvania,2020,"13,002,700",2.4,290.6,11.0
666,Puerto Rico,2020,"3,285,874",-11.8,959.6,4.0
667,Rhode Island,2020,"1,097,379",4.3,"1,061.40",3.0
668,South Carolina,2020,"5,118,425",10.7,170.2,21.0
669,South Dakota,2020,"886,667",8.9,11.7,48.0
670,Tennessee,2020,"6,910,840",8.9,167.6,22.0
671,Texas,2020,"29,145,505",15.9,111.6,26.0
672,Utah,2020,"3,271,616",18.4,39.7,42.0
673,Vermont,2020,"643,077",2.8,69.8,33.0
674,Virginia,2020,"8,631,393",7.9,218.6,16.0
675,Washington,2020,"7,705,281",14.6,115.9,24.0
676,West Virginia,2020,"1,793,716",-3.2,74.6,31.0
677,Wisconsin,2020,"5,893,718",3.6,108.8,27.0
678,Wyoming,2020,"576,851",2.3,5.9,51.0

In [18]:
namus2020

,Case Number,DLC,Last Name,First Name,Missing Age,City,County,State,Biological Sex,Race / Ethnicity,Date Modified,Race/Ethn 1,Race/Ethn 2,Race/Ethn 3,Race/Ethn 4,Race/Ethn 5
4121,MP77387,2020-12-31,Brown,Rupert,42,Riverton,Fremont,WY,Male,American Indian / Alaska Native,2023-04-27,American Indian / Alaska Native,NaN,NaN,NaN,NaN
4122,MP78577,2020-12-30,Fleetwood,Keyara,15,Oklahoma City,Oklahoma,OK,Female,Black / African American,2023-02-12,Black / African American,NaN,NaN,NaN,NaN
4123,MP77291,2020-12-30,Rolle,Shanyea,27,Houston,Harris,TX,Female,Black / African American,2021-03-18,Black / African American,NaN,NaN,NaN,NaN
4124,MP104066,2020-12-30,Clopton,William,33,Tupelo,Pontotoc,MS,Male,White / Caucasian,2023-06-05,White / Caucasian,NaN,NaN,NaN,NaN
4125,MP80732,2020-12-29,Ellis-Sandlin,Kayven,16,Inglis,Levy,FL,Female,White / Caucasian,2022-04-19,White / Caucasian,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5086,MP71494,2020-01-01,Jackson,Johnny,47,Long Island City,Queens,NY,Male,Black / African American,2020-08-11,Black / African American,NaN,NaN,NaN,NaN
5087,MP80267,2020-01-01,Veldhaus,Chad,48,Santa Monica,Los Angeles,CA,Male,White / Caucasian,2021-05-18,White / Caucasian,NaN,NaN,NaN,NaN
5088,MP101316,2020-01-01,Perez,Edber,30,Washington D.C.,District of Columbia,DC,Male,Hispanic / Latino,2023-03-15,Hispanic / Latino,NaN,NaN,NaN,NaN
5089,MP100111,2020-01-01,Mccallion,Leslie,67,Monterey,Monterey,CA,Male,White / Caucasian,2023-05-08,White / Caucasian,NaN,NaN,NaN,NaN
5090,MP103183,2020-01-01,Barksdale,James,39,Kansas City,Jackson,MO,Male,Black / African American,2023-07-27,Black / African American,NaN,NaN,NaN,NaN

In [19]:
states = pd.read_csv('./data/states.csv')
states['Name'] = states.Name.str.strip()

In [20]:
namus2020['State'] = namus2020.State.str.strip()

C:\Users\riley\AppData\Local\Temp\ipykernel_17092\2251865425.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  namus2020['State'] = namus2020.State.str.strip()

In [21]:
pops20state = pd.merge(pops20state, states, left_on='Name', right_on='Name')
pops20state

,Name,Year,Resident Population,Percent Change in Resident Population,Resident Population Density,Resident Population Density Rank,Abbreviation
0,Alabama,2020,"5,024,279",5.1,99.2,29.0,AL
1,Alaska,2020,"733,391",3.3,1.3,52.0,AK
2,Arizona,2020,"7,151,502",11.9,62.9,35.0,AZ
3,Arkansas,2020,"3,011,524",3.3,57.9,36.0,AR
4,California,2020,"39,538,223",6.1,253.7,13.0,CA
5,Colorado,2020,"5,773,714",14.8,55.7,39.0,CO
6,Connecticut,2020,"3,605,944",0.9,744.7,6.0,CT
7,Delaware,2020,"989,948",10.2,508,8.0,DE
8,District of Columbia,2020,"689,545",14.6,"11,280.00",1.0,DC
9,Florida,2020,"21,538,187",14.6,401.4,10.0,FL
10,Georgia,2020,"10,711,908",10.6,185.6,19.0,GA
11,Hawaii,2020,"1,455,271",7.0,226.6,15.0,HI
12,Idaho,2020,"1,839,106",17.3,22.3,46.0,ID
13,Illinois,2020,"12,812,508",-0.1,230.8,14.0,IL
14,Indiana,2020,"6,785,528",4.7,189.4,18.0,IN
15,Iowa,2020,"3,190,369",4.7,57.1,38.0,IA
16,Kansas,2020,"2,937,880",3.0,35.9,43.0,KS
17,Kentucky,2020,"4,505,836",3.8,114.1,25.0,KY
18,Louisiana,2020,"4,657,757",2.7,107.8,28.0,LA
19,Maine,2020,"1,362,359",2.6,44.2,40.0,ME
20,Maryland,2020,"6,177,224",7.0,636.1,7.0,MD
21,Massachusetts,2020,"7,029,917",7.4,901.2,5.0,MA
22,Michigan,2020,"10,077,331",2.0,178,20.0,MI
23,Minnesota,2020,"5,706,494",7.6,71.7,32.0,MN
24,Mississippi,2020,"2,961,279",-0.2,63.1,34.0,MS
25,Missouri,2020,"6,154,913",2.8,89.5,30.0,MO
26,Montana,2020,"1,084,225",9.6,7.4,50.0,MT
27,Nebraska,2020,"1,961,504",7.4,25.5,45.0,NE
28,Nevada,2020,"3,104,614",15.0,28.3,44.0,NV
29,New Hampshire,2020,"1,377,529",4.6,153.8,23.0,NH
30,New Jersey,2020,"9,288,994",5.7,"1,263.00",2.0,NJ
31,New Mexico,2020,"2,117,522",2.8,17.5,47.0,NM
32,New York,2020,"20,201,249",4.2,428.7,9.0,NY
33,North Carolina,2020,"10,439,388",9.5,214.7,17.0,NC
34,North Dakota,2020,"779,094",15.8,11.3,49.0,ND
35,Ohio,2020,"11,799,448",2.3,288.8,12.0,OH
36,Oklahoma,2020,"3,959,353",5.5,57.7,37.0,OK
37,Oregon,2020,"4,237,256",10.6,44.1,41.0,OR
38,Pennsylvania,2020,"13,002,700",2.4,290.6,11.0,PA
39,Puerto Rico,2020,"3,285,874",-11.8,959.6,4.0,PR
40,Rhode Island,2020,"1,097,379",4.3,"1,061.40",3.0,RI
41,South Carolina,2020,"5,118,425",10.7,170.2,21.0,SC
42,South Dakota,2020,"886,667",8.9,11.7,48.0,SD
43,Tennessee,2020,"6,910,840",8.9,167.6,22.0,TN
44,Texas,2020,"29,145,505",15.9,111.6,26.0,TX
45,Utah,2020,"3,271,616",18.4,39.7,42.0,UT
46,Vermont,2020,"643,077",2.8,69.8,33.0,VT
47,Virginia,2020,"8,631,393",7.9,218.6,16.0,VA
48,Washington,2020,"7,705,281",14.6,115.9,24.0,WA
49,West Virginia,2020,"1,793,716",-3.2,74.6,31.0,WV
50,Wisconsin,2020,"5,893,718",3.6,108.8,27.0,WI
51,Wyoming,2020,"576,851",2.3,5.9,51.0,WY

In [22]:
pops20state['Abbreviation'] = pops20state.Abbreviation.str.strip()

In [23]:
namuspop2020 = pd.merge(namus2020, pops20state, left_on='State', right_on='Abbreviation')

In [24]:
namuspop2020 = namuspop2020.drop(['Abbreviation', 'Percent Change in Resident Population'], axis=1)

In [27]:
namuspop2020 = namuspop2020.rename(columns={"State": "State Abbreviation", "Name": "State"})

In [28]:
namuspop2020

,Case Number,DLC,Last Name,First Name,Missing Age,City,County,State Abbreviation,Biological Sex,Race / Ethnicity,...,Race/Ethn 1,Race/Ethn 2,Race/Ethn 3,Race/Ethn 4,Race/Ethn 5,State,Year,Resident Population,Resident Population Density,Resident Population Density Rank
0,MP77387,2020-12-31,Brown,Rupert,42,Riverton,Fremont,WY,Male,American Indian / Alaska Native,...,American Indian / Alaska Native,NaN,NaN,NaN,NaN,Wyoming,2020,"576,851",5.9,51.0
1,MP72568,2020-07-07,Pedry,Paul,43,Casper,Natrona,WY,Male,White / Caucasian,...,White / Caucasian,NaN,NaN,NaN,NaN,Wyoming,2020,"576,851",5.9,51.0
2,MP78577,2020-12-30,Fleetwood,Keyara,15,Oklahoma City,Oklahoma,OK,Female,Black / African American,...,Black / African American,NaN,NaN,NaN,NaN,Oklahoma,2020,"3,959,353",57.7,37.0
3,MP78576,2020-12-29,Stoetzel,Bryon,14,Oklahoma City,Oklahoma,OK,Male,White / Caucasian,...,White / Caucasian,NaN,NaN,NaN,NaN,Oklahoma,2020,"3,959,353",57.7,37.0
4,MP76842,2020-12-19,Harris,Paydenn,14,Norman,Cleveland,OK,Male,White / Caucasian,...,White / Caucasian,NaN,NaN,NaN,NaN,Oklahoma,2020,"3,959,353",57.7,37.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
965,MP71058,2020-06-11,Price,Tarie,NaN,Gretna,Sarpy,NE,Female,Black / African American,...,Black / African American,NaN,NaN,NaN,NaN,Nebraska,2020,"1,961,504",25.5,45.0
966,MP75108,2020-03-23,Thieme,Robert,55,Lincoln,Lancaster,NE,Male,White / Caucasian,...,White / Caucasian,NaN,NaN,NaN,NaN,Nebraska,2020,"1,961,504",25.5,45.0
967,MP105020,2020-04-13,Jean-Marie,Ralph,38,Barre,Washington,VT,Male,Black / African American,...,Black / African American,NaN,NaN,NaN,NaN,Vermont,2020,"643,077",69.8,33.0
968,MP67626,2020-03-17,Grazewski,Amanda,23,Derry,Rockingham,NH,Female,White / Caucasian,...,White / Caucasian,NaN,NaN,NaN,NaN,New Hampshire,2020,"1,377,529",153.8,23.0
969,MP66225,2020-01-15,Bailey,April,36,Nashua,Hillsborough,NH,Female,White / Caucasian,...,White / Caucasian,NaN,NaN,NaN,NaN,New Hampshire,2020,"1,377,529",153.8,23.0

In [30]:
namuspop2020.to_csv('./data/namuspop2020.csv')